/*
MIT License

Copyright (c) 2022 Iuriiiii

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/**
 * Enum representing the different types of tokens.
 */
export enum TokenType {
  UNKNOWN = "unknown",
  SPACE = "space",
  STRING = "string",
  IDENTIFIER = "identifier",
  INSTRUCTION = "instruction",
  NUMBER = "number",
  OPERATOR = "operator",
  SEPARATOR = "separator",
  EOL = "eol",
  EOF = "eof",
}

/**
 * Represents the position of a token in the source code.
 */
export interface ITokenPosition {
  /**
   * The column number (1-indexed).
   */
  x: number;

  /**
   * The line number (1-indexed).
   */
  y: number;
}

/**
 * Represents a token generated by the tokenizer.
 */
export interface IToken {
  /**
   * The text content of the token.
   */
  text: string;

  /**
   * The position where the token starts.
   */
  pos: ITokenPosition;

  /**
   * The type of the token.
   */
  type: TokenType;
}

/**
 * Namespace containing tokenizer logic and constants.
 */
export namespace Tokenizer {
  const SPACES = " \t\r\n" as const;
  const SEPARATORS = "\\:;[](){},." as const;
  const OPERATORS = "+-/*^%=!" as const;
  const NUMBERS = "0123456789" as const;
  const CHARACTERS =
    "abcdefghijklmnñopqrstuvwxyzáéíóúABCDEFGHIJKLMNÑOPQRSTUVWXYZÁÉÍÓÚ" as const;

  /**
   * Options for the tokenizer.
   */
  export interface ITokenizerOptions {
    /**
     * String containing characters to be treated as spaces.
     */
    spaces: string;

    /**
     * String containing characters to be treated as operators.
     */
    operators: string;

    /**
     * String containing characters to be treated as separators.
     */
    separators: string;
  }

  /**
   * Internal arguments for resizing the current token.
   */
  interface IResizeIfArguments {
    /**
     * The list of completed tokens.
     */
    list: IToken[];

    /**
     * The token currently being built.
     */
    currentToken: IToken;

    /**
     * The target token type.
     */
    targetType: TokenType;

    /**
     * The current character being processed.
     */
    char: string;

    /**
     * The current position in the source.
     */
    pos: ITokenPosition;
  }

  /**
   * Finalizes the current token and starts a new one if the type changes.
   */
  function resizeIf(args: IResizeIfArguments): IToken {
    const { list, currentToken, targetType, char, pos } = args;
    const isEof = currentToken.type === TokenType.EOF;

    if (isEof) {
      const eofToken = {
        ...currentToken,
        text: "",
        type: targetType,
      };

      return eofToken;
    }

    const isOperatorDash = targetType === TokenType.OPERATOR &&
      char === "-";
    const isIdentifier = currentToken.type === TokenType.IDENTIFIER;
    const isIdentifierDash = isOperatorDash && isIdentifier;

    const isNumber = targetType === TokenType.NUMBER;
    const isIdentifierNumber = isNumber && isIdentifier;

    const isSeparator = currentToken.type === TokenType.SEPARATOR;
    const isTypeDifferent = currentToken.type !== targetType;
    const shouldPushToken = isSeparator || isTypeDifferent;

    switch (true) {
      case isIdentifierDash:
        break;

      case isIdentifierNumber:
        break;

      case shouldPushToken: {
        list.push(currentToken);

        const newToken = {
          text: "",
          pos: { ...pos },
          type: targetType,
        };

        return newToken;
      }

      default:
        break;
    }

    return currentToken;
  }

  /**
   * Maps a character to its corresponding token type.
   */
  function charToType(
    char: string,
    options: Partial<ITokenizerOptions>,
  ): TokenType {
    const spacesToUse = options.spaces || SPACES;
    const separatorsToUse = options.separators || SEPARATORS;
    const operatorsToUse = options.operators || OPERATORS;

    switch (true) {
      case NUMBERS.includes(char):
        return TokenType.NUMBER;

      case separatorsToUse.includes(char):
        return TokenType.SEPARATOR;

      case operatorsToUse.includes(char):
        return TokenType.OPERATOR;

      case CHARACTERS.includes(char):
        return TokenType.IDENTIFIER;

      case spacesToUse.includes(char): {
        const isEol = char === "\n";

        if (isEol) {
          return TokenType.EOL;
        }

        return TokenType.SPACE;
      }

      default:
        return TokenType.UNKNOWN;
    }
  }

  /**
   * Tokenizes the provided source string.
   */
  export function tokenizate(
    source: string,
    options: Partial<ITokenizerOptions> = {},
  ): IToken[] {
    let currentToken: IToken = {
      text: "EOF",
      pos: { x: 1, y: 1 },
      type: TokenType.EOF,
    };

    const result: IToken[] = [];
    const currentPos: ITokenPosition = { x: 1, y: 1 };
    let isInsideString = false;

    for (let i = 0; i < source.length; i++) {
      const char = source[i];

      switch (true) {
        case char === '"': {
          isInsideString = !isInsideString;

          if (isInsideString) {
            currentToken = resizeIf({
              list: result,
              currentToken,
              targetType: TokenType.STRING,
              char,
              pos: currentPos,
            });
          }
          break;
        }

        case isInsideString:
          break;

        default: {
          const type = charToType(char, options);
          const isKnownType = type !== TokenType.UNKNOWN;

          if (isKnownType) {
            const isEol = type === TokenType.EOL;

            if (isEol) {
              currentPos.y++;
              currentPos.x = 1;
            }

            currentToken = resizeIf({
              list: result,
              currentToken,
              targetType: type,
              char,
              pos: currentPos,
            });
          } else {
            const isCarriageReturn = char === "\r";

            if (isCarriageReturn) {
              // Ignore \r
              currentPos.x++;
              continue;
            }

            currentToken = resizeIf({
              list: result,
              currentToken,
              targetType: TokenType.UNKNOWN,
              char,
              pos: currentPos,
            });
          }
          break;
        }
      }

      currentToken.text += char;
      currentPos.x++;
    }

    result.push(currentToken);

    const lastToken = result.at(-1);
    const isLastTokenNotEof = lastToken &&
      lastToken.type !== TokenType.EOF;

    if (isLastTokenNotEof) {
      const eofToken = {
        text: "EOF",
        type: TokenType.EOF,
        pos: currentPos,
      };

      result.push(eofToken);
    }

    return result;
  }
}
